### ISSUE TITLE
I encountered the following error in docker.

### ISSUE THREAD

**Issue by tianvier** [piercus/step-function-worker#17]
**Worker:**
```
let work_func = async function (event, callback, heartbeat) {

  heartbeat()
  console.log(event)

  doSomthing...

  heartbeat()
  callback(null, event)
}

```

```
let worker = new StepFunctionWorker({
  activityArn: 'activity',
  workerName: 'task',
  fn: work_func,
  concurrency: 200, // default is 1
  awsConfig: {
    region: 'us-east-1',
  },
  autoStart: true,
})
```

**Docker Containers**
```
CPU Units: 1500
Hard/Soft memory limits (MiB) : 3500/--

```

**Logs:**
```
06:27:09 /home/stepuser/node/node_modules/aws-sdk/lib/request.js:31
06:27:09 throw err;
06:27:09 ^
06:27:09 Error: Unhandled "error" event. ([object Object])
06:27:09 at Worker.emit (events.js:186:19)
06:27:09 at Response.stepfunction.sendTaskHeartbeat.err (/home/stepuser/node/node_modules/step-function-worker/lib/worker.js:211:9)
06:27:09 at Request.<anonymous> (/home/stepuser/node/node_modules/aws-sdk/lib/request.js:364:18)
06:27:09 at Request.callListeners (/home/stepuser/node/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
06:27:09 at Request.emit (/home/stepuser/node/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
06:27:09 at Request.emit (/home/stepuser/node/node_modules/aws-sdk/lib/request.js:683:14)
06:27:09 at Request.transition (/home/stepuser/node/node_modules/aws-sdk/lib/request.js:22:10)
06:27:09 at AcceptorStateMachine.runTo (/home/stepuser/node/node_modules/aws-sdk/lib/state_machine.js:14:12)
06:27:09 at /home/stepuser/node/node_modules/aws-sdk/lib/state_machine.js:26:10
06:27:09 at Request.<anonymous> (/home/stepuser/node/node_modules/aws-sdk/lib/request.js:38:9)
```

**Comment by piercus** [comment]
Hello @tianvier,

Thanks for this feedback.

Are you able to reproduce the error outside of docker (it would be great if you can make a unit test for this) ?

What happens if you set concurrency to '3' instead of `200`, are you still facing this error ?

It might be related to https://github.com/piercus/step-function-worker/issues/16

**Comment by tianvier** [comment]
I know the reason.

I set the timeout for `step function states  && activity`

```
{
  "Comment": "A Hello World example of the Amazon States Language using a Pass state",
  "StartAt": "HelloWorld",
  "TimeoutSeconds": 60,
  "States": {
    "HelloWorld": {
      "Type": "Task",
      "Resource": "activity",
      "TimeoutSeconds": 60,
      "End": true
    }
  }
}
```
**Worker**
```
let work_func = async function (event, callback, heartbeat) {

  heartbeat()
  console.log(event)

  doSomthing...
 
  // error !!!  Error: Unhandled "error" event. ([object Object])   at Worker.emit (events.js:186:19)
  heartbeat() 
  callback(null, event)
}

```

Step function timeout automatically fails when the second execution of `heartbeat ()` will appear the above error

**Comment by piercus** [comment]
Ok, great !

Anyway the error message `Error: Unhandled "error" event. ([object Object])` is not explicit enough.

**Comment by tianvier** [comment]
sorry.  I have no handle the error event...

so the program is terminated.

something simple like :
```
let worker = new StepFunctionWorker({
  activityArn: 'activity',
  workerName: 'task',
  fn: work_func,
  concurrency: 200, // default is 1
  awsConfig: {
    region: 'us-east-1',
  },
  autoStart: true,
})


worker.on('error', function(err){
  console.log("error ", err)
});
```
would do.

thank you very much.
